// <auto-generated />
using System;
using DecentRetroTool.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DecentRetroTool.Api.Migrations
{
    [DbContext(typeof(RetroDbContext))]
    [Migration("20251101092758_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Retro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Retros");
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RetroId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Note", b =>
                {
                    b.HasOne("DecentRetroTool.Api.Data.Models.Section", null)
                        .WithMany("Notes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Retro", b =>
                {
                    b.HasOne("DecentRetroTool.Api.Data.Models.Team", null)
                        .WithMany("Retros")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Section", b =>
                {
                    b.HasOne("DecentRetroTool.Api.Data.Models.Retro", null)
                        .WithMany("Sections")
                        .HasForeignKey("RetroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Retro", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Section", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("DecentRetroTool.Api.Data.Models.Team", b =>
                {
                    b.Navigation("Retros");
                });
#pragma warning restore 612, 618
        }
    }
}
